import item1 from "../../assets/images/item/item_1.jpg";
import profilePhoto from "../../assets/images/icons/user-icon.svg";

export const items = [
  {
    image: item1,
    title: "Hammer",
    price: "₱ 600",
    owner: "Alice Reyes",
    ownerImage: profilePhoto,
    rating: 4,
    tags: ["Tool", "Hardware", "Essential"],
  },
  {
    image: item1,
    title: "Screwdriver",
    price: "₱ 300",
    owner: "John Doe",
    ownerImage: profilePhoto,
    rating: 5,
    tags: ["Tool", "Hardware", "Handy"],
  },
  {
    image: item1,
    title: "Pliers",
    price: "₱ 450",
    owner: "Maria Santos",
    ownerImage: profilePhoto,
    rating: 3,
    tags: ["Tool", "Hardware", "Essential"],
  },
  {
    image: item1,
    title: "Chisel",
    price: "₱ 350",
    owner: "Robert Garcia",
    ownerImage: profilePhoto,
    rating: 2,
    tags: ["Tool", "Hardware", "Precision"],
  },
  {
    image: item1,
    title: "Saw",
    price: "₱ 700",
    owner: "Liza Cruz",
    ownerImage: profilePhoto,
    rating: 4,
    tags: ["Tool", "Hardware", "Cutting"],
  },
  {
    image: item1,
    title: "Level",
    price: "₱ 400",
    owner: "Carlos Mendez",
    ownerImage: profilePhoto,
    rating: 5,
    tags: [
      "Tool",
      "Hardware",
      "Measurement",
      "Hardware",
      "Measurement",
      "Hardware",
      "Measurement",
    ],
  },
];
