// src/components/MyRentals/data.js
import item1 from "../../assets/images/item/item_1.jpg";

export const rentalItems = [
    {
        id: 1,
        title: "Calculus Textbook",
        borrower: "John Doe",
        requestDate: "July 1, 2024",
        image: item1,
        status: "Pending",
      },
      {
        id: 2,
        title: "Calculus Textbook",
        borrower: "Michael Lee",
        requestDate: "July 1, 2024",
        image: item1,
        status: "Request",
      },
      {
        id: 3,
        title: "Calculus Textbook",
        borrower: "John Doe",
        requestDate: "July 1, 2024",
        handoverDate: "July 3, 2024",
        location: "TUP Manila Campus",
        image: item1,
        status: "Hand Over",
      },
      {
        id: 4,
        title: "Calculus Textbook",
        lender: "Michael Lee",
        requestDate: "July 1, 2024",
        handoverDate: "July 3, 2024",
        location: "TUP Manila Campus",
        image: item1,
        status: "Hand Over",
      },
      {
        id: 5,
        title: "Calculus Textbook",
        borrower: "John Doe",
        returnDate:"July 10, 2024",
        image: item1,
        status: "Return",
      },
      {
        id: 6,
        title: "Calculus Textbook",
        lender: "Michael Lee",
        returnDate:"July 10, 2024",
        image: item1,
        status: "Return",
      },
      {
        id: 7,
        title: "Calculus Textbook",
        borrower: "John Doe",
        rentalPeriod:"July 1, 2024-July 10, 2024",
        image: item1,
        status: "Completed",
      },
      {
        id: 8,
        title: "Calculus Textbook",
        lender: "Michael Lee",
        rentalPeriod:"July 1, 2024-July 10, 2024",
        image: item1,
        status: "Completed",
      },
      {
        id: 9,
        title: "Calculus Textbook",
        borrower: "John Doe",
        rentalPeriod:"July 1, 2024-July 10, 2024",
        image: item1,
        status: "Reviewed",
      },
      {
        id: 10,
        title: "Calculus Textbook",
        lender: "Michael Lee",
        rentalPeriod:"July 1, 2024-July 10, 2024",
        image: item1,
        status: "Reviewed",
      },
      {
        id: 11,
        title: "Calculus Textbook",
        borrower: "John Doe",
        cancellation:"July 10, 2024",
        image: item1,
        status: "Cancelled",
        reason: " ",
      },
      {
        id: 12,
        title: "Calculus Textbook",
        lender: "Michael Lee",
        cancellation:"July 10, 2024",
        image: item1,
        status: "Cancelled",
        reason: " ",
      },
];

export const filterOptions = ["Request", "Hand Over", "Return", "Completed", "Reviewed", "Cancelled"];
